### PR TITLE
Option to not print parameter values to console

### PR DESCRIPTION
**Pull request by TobiasKAndersen**
Include option not to print parameter values to console during model simulations.
This will fix errors caused by limited internal memory.
The option is currently only implemented in evaluate2 function. For user ease, this should be threaded to input in console.

### CODE REVIEW

**Review by jornbr — COMMENTED** [review]
That's a valuable addition, since it caused very hard to debug memory leaks in the past (some shells buffering all output for very long runs and running out of memory). However, there are a lot of print statements in that routine. Should they not all be subject to "if print_verbose:"? Also I'd prefer "verbose", as that convention is used in various other parts of parsac. Any reason why it should be "print_verbose"?

Cheers,

Jorn

**Comment by TobiasKAndersen** [comment]
Great, that is good to hear. No special reason for the "print_verbose" instead of "verbose". I am still new to software development, so I am not aware of most conventions. I will change "print_verbose" to "verbose". Regarding other print statements, I only included verbose for print of 'Evaluating fitness with parameter set [%s]' as this solved my problem with running out of memory. If you prefer, I will be happy to go through the entire routine and include verbose conditions for all other print statements?

**Comment by jornbr** [comment]
Thanks. If you change "print_verbose" to "verbose" as you propose, that'd be fine for now. I'll then merge in and may go in afterwards to make additional print statements dependent on the "verbose" (I'd like to review them case by case)

Cheers,

Jorn

**Comment by TobiasKAndersen** [comment]
I have now updated the pull request as described.

Cheers,
Tobias

**Comment by jornbr** [comment]
By the way, it looks like this currently would be a hidden argument, not accessible to users without editing code in other places. How have you been using it? (by editing code elsewhere? should those edits go into the PR?)

Jorn

**Comment by TobiasKAndersen** [comment]
My PR was incorrect, it should have stated verbose = False in the evaluate2 function. I did not edit anywhere else in the code. This is also in line with other verbose conditions in the script.
Sorry for error!

**Comment by jornbr** [comment]
Actually as default I'd prefer verbose=True to preserve the original behaviour (can you revert hat last change?) But I was thinking that ultimately, this should likely be under control of a --quiet option to "parsac run", and was wondering if you were using something like that already

Jorn

**Comment by TobiasKAndersen** [comment]
No, I only had set verbose=False. I'll reverse back

**Comment by TobiasKAndersen** [comment]
I could not figure out how to remove change, so included another edit

**Pull request merged**
