### PR TITLE
Lets parsac create pkl file with SA results

### PR DESCRIPTION
**Pull request by TobiasKAndersen**
After finished SA analysis step, a pkl file named 'SA_results.pkl' is created, so the user can post-process the results.

### CODE REVIEW

**Review by jornbr — COMMENTED** [review]
Thanks, it seems fine to store the analysis result as pickle if useful to you. However, I'd like that to be controlled by a command line option (--pickle?), which takes the path to save to (as opposed to hardcoded SA_results.pkl). If not provided the pickling would not be done. Also - why do the parameter names need to be stored as numpy array instead of a python list? And why "Parameter" (singular) as opposed to e.g. "parameters" or "names"?

Cheers,

Jorn

**Comment by TobiasKAndersen** [comment]
Of course, including the option to create a pickle with the results as a command line is a better solution than hard coding it. 

There was no reason for numpy array instead of python list. And feel free to change the naming.

**Comment by TobiasKAndersen** [comment]
Thanks for your comments Jorn.
I will incorporate your comments and and do a new pull request.

**Comment by TobiasKAndersen** [comment]
Hi Jorn,
I have now included the pickle option in the parser by following your guidance.
the variable 'analysis' with hold SALib analysis results is still outputted from analyze function, but is now only used if pickle path is given. Is this an ok solution for you?

Cheers,
Tobias

**Comment by TobiasKAndersen** [comment]
Thanks for the hint Karsten

**Comment by jornbr** [comment]
Looks good to me now. Does it run ok,, with and without --pickle?

Jorn

**Comment by TobiasKAndersen** [comment]
With the last update, it runs without error - both with and without --pickle

**Pull request merged**
